### ISSUE TITLE
List of DPs with data that looks OK

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#46]
* [x] AsDB but see #43 
* [x] Belgium but see #44
* [ ] Danida
* [x] DFID
* [x] Canada
* [ ] Germany
* [x] EIB but see #44
* [x] EU but see #45 
* [x] Gavi but see #44 
* [x] Global Fund
* [x] Netherlands
* [ ] Sweden / Sida
* [ ] Switzerland / SDC
* [x] UN Habitat but see #44
* [ ] UN Women
* [x] UNDP but see #42
* [ ] UNFPA
* [ ] USAID
* [x] World Bank
* [x] World Food Programme but see #42
